# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "node1" do |node1|
    node1.vm.box = "precise32"
    node1.vm.network "private_network", ip: "192.168.10.11"
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "precise32"
    node2.vm.network "private_network", ip: "192.168.10.12"
  end

  config.vm.define "lb" do |lb|
    lb.vm.box = "precise32"
    lb.vm.hostname = "lb"
    lb.vm.network "private_network", ip: "192.168.10.10"
  end
end
