- name: Setup loadbalancers
  hosts: loadbalancers
  sudo: yes
  roles:
    - nginx

- name: Setup wordie nodes
  hosts: wordie_nodes
  sudo: true
  roles:
    - { role: java-service, service_name: wordie, http_port: 3000 }
